### ISSUE TITLE
[Bug]: Migrate Akavache 10 → 11

### ISSUE THREAD

**Issue by dmitriypetrukk** [reactiveui/Akavache#1140]
### Describe the bug 🐞

Hi, I’m upgrading my MAUI application from .NET 8 → .NET 9 and Akavache 10 → 11.

According to the documentation, Akavache v11 should automatically migrate
the legacy v10 SQLite database the first time it is accessed:

https://github.com/reactiveui/Akavache/blob/main/docs/migration-v10-to-v11.md

However, the migration does not happen — Akavache always creates a brand new
empty database. As a result, all users get logged out after the update because
the cached authentication token is lost.

I tested both:
- iOS Simulator
- real iOS device via TestFlight

In both cases the v11 app does *not* detect or migrate the existing SQLite DB.

I attach:
- my old Akavache v10 CacheManager (working)
- my new Akavache v11 CacheManager

Files:
- [cacheManager-OLD.rtf](https://github.com/user-attachments/files/23629507/cacheManager-OLD.rtf)
- [cacheManager.rtf](https://github.com/user-attachments/files/23629508/cacheManager.rtf)

I want to understand:
- Is my migration code correct?
- Is auto-migration supported when using `WithAkavacheCacheDatabase`?
- Is there an additional step required to enable migration?
- Or is this possibly a bug in v11?

Thank you!

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

When upgrading from Akavache v10 to v11, the new version should automatically
detect and migrate the existing legacy SQLite cache database created by v10,
as described in the migration guide.

After launching the app with Akavache v11 for the first time, all previously 
stored data (including authentication tokens) should remain available, and 
users should stay logged in without needing to re-authenticate.

### IDE

Rider macOS

### Operating system

Mac OS

### Device

iPhone

**Comment by WilliamWatterson86** [comment]
@dmitriypetrukk - were you able to access your old data?  Having same issue here and was hoping you had a workaround or steps you followed?

**Comment by dmitriypetrukk** [comment]
@WilliamWatterson86 Hi! Unfortunately, we weren’t able to migrate Akavache SQLite data directly from v10 to v11.

As a workaround, we temporarily extracted the critical data from the v10 cache and stored it in SecureStorage, then restored it into Akavache after initializing v11.

It’s not ideal, but this was the only reliable way we found to preserve user data during the upgrade. We couldn’t get the built-in migration to work without data loss.

**Comment by glennawatson** [comment]
This issue is caused by V11 using isolated storage directories by default, which differ from V10's file locations. The database files exist but V11 is looking in the wrong directory.

**Fix:** Use `WithLegacyFileLocation()` in the builder chain so V11 looks in the same directories V10 used:

```csharp
AppBuilder.CreateSplatBuilder()
    .WithAkavacheCacheDatabase<NewtonsoftBsonSerializer>(builder =>
        builder.WithApplicationName("SameAsV10App")
               .WithLegacyFileLocation()    // Required for V10→V11 migration
               .WithSqliteProvider()
               .WithSqliteDefaults());
```

V11 includes backward-compatible reads from V10's `CacheElement` table — once the database file is found at the legacy path, your existing data (including auth tokens) will be read transparently.

The migration documentation has been updated to document this requirement. We've also fixed a bug where `CreateSqliteCache` didn't create the legacy cache directory if it didn't already exist.

**Comment by RenatGaliew** [comment]
[glennawatson](https://github.com/glennawatson), If I have an old file called userblob.db and other files on 8v, and I set "WithLegacyFileLocation," but the old db still doesn't load, what should I do? All my data is in UserAccount. I call it all like this:

 AppBuilder.CreateSplatBuilder()
     .WithAkavacheCacheDatabase<NewtonsoftBsonSerializer>(akavacheBuilder =>
         akavacheBuilder.WithApplicationName("my_app_name")
             .WithLegacyFileLocation()
             .WithSqliteProvider() 
             .WithSqliteDefaults());

Old akavache version on xamarin netstandard2.1:  8.1.1
New akavache version on MAUI net10.0-ios26.0.:  11.6.1

**Comment by glennawatson** [comment]
@RenatGaliew We've identified the root cause — it's not just the directory paths but also the **database filenames** that changed between versions:

- V10: `blobs.db`, `userblobs.db`, `secret.db`
- V11: `LocalMachine.db`, `UserAccount.db`, `Secure.db`

So even with `WithLegacyFileLocation()`, V11 is looking for the wrong filename in the right directory.

We're building a new **`Akavache.V10toV11`** NuGet package that provides:

1. **`WithV10FileNames()`** — points V11 at the exact old database files so your data is found immediately (V11 already knows how to read the old `CacheElement` table).
2. **`MigrateFromV10()`** — a one-time migration utility that copies data from old V10 databases into new V11 databases, with optional re-serialization from BSON to System.Text.Json (AOT-compatible).

This is in a separate assembly so it doesn't pollute the core architecture. Will update this issue when the package is available.

**Comment by RenatGaliew** [comment]
@glennawatson Could you please tell me approximately how long I'll have to wait for this package? Where can I find it and how can I use it?

**Comment by glennawatson** [comment]
@RenatGaliew Releasing v12 which has this module. It will be in GitHub packages while it is beta release which you can test from there if you like, would appreciate feedback.

**Comment by WilliamWatterson86** [comment]
@glennawatson - thankyou for the developing the migration package.  

I have tried the lastest v13.  

My file names seem to be different than what you are looking for so the db is never deleted even though I have passed in the options to delete the db after migration.

Here is how I initalize the cache:



```
private static void InitializeAvacache()
{
    AppBuilder.CreateSplatBuilder()
        .WithAkavacheCacheDatabase<NewtonsoftBsonSerializer>(
        builder =>
        {
            builder.WithLegacyFileLocation()
                    .UseForcedDateTimeKind(DateTimeKind.Unspecified)
                    .WithSqliteProvider()
                    .WithSqliteDefaults()
                    .MigrateFromV10(new V10MigrationOptions(true, true, true, true, true, msg => Console.WriteLine(msg)));
        },
    Common.Constants.Constants.AppName);
}
```

I cloned the repo and made this edit to the GetV10DatabasePath method inside V10MigrationHelpers.cs and now it seems to work well for me.

```
internal static string? GetV10DatabasePath(IAkavacheBuilder builder, string cacheName)
    {
        var directory = builder.GetLegacyCacheDirectory(cacheName);
        var defaultPath = directory is null || string.IsNullOrWhiteSpace(directory)
            ? null
            : Path.Combine(directory, V10FileNameMap.GetV10FileName(cacheName));

        if (defaultPath is null || !File.Exists(defaultPath))
        {
            //Default path is null - trying to get fallback

            var documents =
                Environment.GetFolderPath(Environment.SpecialFolder.Personal);

            string? fallbackPath = cacheName switch
            {
                "LocalMachine" => Path.Combine(
                    documents,
                    builder.ApplicationName!,
                    "BlobCache",
                    "blobs.db"),

                "UserAccount" => Path.Combine(
                    documents,
                    ".config",
                    builder.ApplicationName!,
                    "BlobCache",
                    "userblobs.db"),

                "Secure" => Path.Combine(
                    documents,
                    ".config",
                    builder.ApplicationName!,
                    "SecretCache",
                    "secret.db"),

                _ => null
            };

            if (!string.IsNullOrWhiteSpace(fallbackPath) &&
                File.Exists(fallbackPath))
            {
                // Using fallback V10 path

                return fallbackPath;
            }
        }

        // Using default V10 path
        return defaultPath;
    }
```


I have used Akavache since the very early packages and this is a project migrated from Xamarin last year - maybe this is why my path is different than what you are looking for?

Thanks
